version: '3'
services:
  mongo_db:
    container_name: crud_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - "5000:5000"
    environment: 
      PORT: 5000
      DB_URI: mongodb://mongo_db:27017/Mydb
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
